### ISSUE TITLE
Idea to make selecting inventories easier

### ISSUE THREAD

**Issue by chainingsolid** [Vswe/ModJam3#61] opened 2014-05-27 00:50 UTC
When trying  selecting inventories when I have a lot of them hooked up it's very hard to tell which inventory is which. I would like a feature that would let you name blocks in the world then have the manger GUI put that name on the tool tip for that inventory. I wouldn't mind trying to add that feature myself if allowed. All I'm looking for here is a solution to having to write down cords of blocks then find that block in the manger's GUI when I have a ton of inventories hooked up to a manger. If you have questions rely to this I'll make an effort of checking this often.

**Comment by Vswe** [comment] 2014-05-27 10:10
Duplicate of issue #13

**Closed as completed by Vswe** 2014-05-27 10:10 UTC
Labels: duplicate
